### ISSUE TITLE
User option returning null.

### ISSUE THREAD

**Issue by bagelwastaken** [bagelwastaken/kekbot#15]
File location: Src/Commands/Games/rps.js
Error: When trying to pull the user slash command choice, the entry returns null. 

<img width="597" alt="image" src="https://user-images.githubusercontent.com/78277278/168466437-6b0e67f5-0a4b-4c31-b07e-c834298d86ad.png">
<img width="260" alt="image" src="https://user-images.githubusercontent.com/78277278/168466468-01d20048-d0dc-4558-8e66-f9385f40ec18.png">

**Comment by bagelwastaken** [comment]
Currently revising for exams, I'll try and see to this when I get the chance to.

**Comment by MichaelSmith-2021** [comment]
There is a typo on line 22, you mistype the option name. Change it to
```js
... = interaction.options.get('choice');
```

**Comment by bagelwastaken** [comment]
> There is a typo on line 22, you mistype the option name. Change it to
> 
> ```js
> ... = interaction.options.get('choice');
> ```

Ah, thank you so much for pointing that out.
